import { useEffect, useMemo, useState } from 'react';
import { addRecord, listRecords, removeRecord, updateRecord } from '../data/genericRecords';
import { modules } from '../config/modules';
import { getAnonymousUser, isSupabaseConfigured, supabase } from '../data/supabaseClient';

const moneyModules = new Set(['budget', 'subscriptions', 'savings', 'net-worth', 'investments']);
const units = (module) => moneyModules.has(module.id) ? 'USD' : module.entryTracker?.value.unit ?? 'items';

export default function Goals() {
  const [user, setUser] = useState(null); const [goals, setGoals] = useState([]); const [totals, setTotals] = useState({}); const [title, setTitle] = useState(''); const [moduleId, setModuleId] = useState('savings'); const [target, setTarget] = useState(''); const [dueAt, setDueAt] = useState(''); const [status, setStatus] = useState('');
  const refresh = async (active = user) => { if (!active) return; const [stored, entries] = await Promise.all([listRecords('goals', active.id, 'goals'), supabase.from('entry_records').select('module_id,value,metadata').eq('user_id', active.id)]); setGoals(stored); const next = {}; (entries.data ?? []).forEach((entry) => { if (entry.metadata?.kind === 'portfolio_snapshot') return; next[entry.module_id] = (next[entry.module_id] ?? 0) + Number(entry.value); }); setTotals(next); };
  useEffect(() => { if (isSupabaseConfigured) getAnonymousUser().then(async (active) => { setUser(active); await refresh(active); }).catch((error) => setStatus(error.message)); }, []);
  const selected = modules.find((module) => module.id === moduleId);
  async function add(event) { event.preventDefault(); if (!title.trim() || !user) return; try { await addRecord('goals', { user_id: user.id, module_id: 'goals', title, target_module_id: moduleId, target_value: target ? Number(target) : null, target_unit: units(selected), due_at: dueAt || null, is_complete: false }); setTitle(''); setTarget(''); setDueAt(''); await refresh(); } catch (error) { setStatus(error.message.includes('target_value') ? 'Run goals-rich-migration.sql in Supabase, then try again.' : error.message); } }
  const activeGoals = useMemo(() => goals.filter((goal) => !goal.is_complete), [goals]);
  return <main className="tracker-shell"><section className="suite-grid goals-grid"><header className="suite-header"><div><span className="eyebrow">Across your modules</span><h1>Goals</h1></div><small>{activeGoals.length} active</small></header><form className="suite-card composer-card" onSubmit={add}><span className="section-label">Create a measurable goal</span><label>Goal title<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Build my emergency fund" /></label><label>Track module<select value={moduleId} onChange={(e) => setModuleId(e.target.value)}>{modules.filter((module) => module.engine === 'entryTracker').map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></label><label>Target ({units(selected)})<input type="number" min="0" value={target} onChange={(e) => setTarget(e.target.value)} /></label><label>Target date <span className="optional">optional</span><input type="date" value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></label><button>Add goal</button></form><section className="suite-card suite-records"><span className="section-label">Your goals</span><ul>{goals.map((goal) => { const current = totals[goal.target_module_id] ?? 0; const progress = goal.target_value ? Math.min(100, current / Number(goal.target_value) * 100) : 0; return <li key={goal.id}><span><strong>{goal.title}</strong><small>{modules.find((module) => module.id === goal.target_module_id)?.title ?? 'Module'}{goal.target_value ? ` · ${current.toLocaleString()} / ${Number(goal.target_value).toLocaleString()} ${goal.target_unit ?? ''}` : ''}{goal.due_at ? ` · due ${new Date(goal.due_at).toLocaleDateString()}` : ''}</small>{goal.target_value ? <div className="progress"><i style={{ width: `${progress}%` }} /></div> : null}</span><button onClick={() => updateRecord('goals', goal.id, { is_complete: !goal.is_complete }).then(refresh)}>{goal.is_complete ? 'Reopen' : 'Done'}</button><button onClick={() => removeRecord('goals', goal.id).then(refresh)}>×</button></li>; })}</ul>{!goals.length && <p className="empty-copy">Turn a tracker into a concrete next milestone.</p>}</section>{status && <p className="status">{status}</p>}</section></main>;
}
