import { useEffect, useMemo, useState } from 'react';
import { addRecord, listRecords, removeRecord, updateRecord } from '../data/genericRecords';
import { getAnonymousUser, isSupabaseConfigured } from '../data/supabaseClient';
import StreakCalendar from '../components/StreakCalendar';
import { applyAutoFields, completionFieldPatch, matchesConfiguredFilter, namedStreakScope, recurrenceField } from './genericEngineBehavior';

const tableFor = { checklist: 'checklist_items', streakTracker: 'streak_checkins', savedItems: 'saved_items', dueDateTracker: 'due_items' };
const labelFor = { checklist: 'Add item', streakTracker: 'Check in today', savedItems: 'Save item', dueDateTracker: 'Add reminder' };
const day = (date = new Date()) => date.toISOString().slice(0, 10);
const addDays = (date, amount) => new Date(date.getFullYear(), date.getMonth(), date.getDate() + amount);
const values = (record) => record.fields ?? record.metadata ?? {};

function Field({ field, value, onChange }) { return <label>{field.label}{field.type === 'select' ? <select required={field.required} value={value ?? ''} onChange={(e) => onChange(e.target.value)}><option value="">Select...</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.required} type={field.type ?? 'text'} value={value ?? ''} onChange={(e) => onChange(e.target.value)} />}</label>; }
function streak(records) { let count = 0; for (let offset = 0; offset < 730; offset += 1) { if (!records.some((record) => record.completed_on === day(addDays(new Date(), -offset)))) break; count += 1; } return count; }
function checklistHistoryLabel(record) { if (!record.is_complete) return ''; if (record.archived_at) return `Archived ${new Date(record.archived_at).toLocaleDateString()}`; if (record.completed_at) return `Completed ${new Date(record.completed_at).toLocaleDateString()}`; return 'Completed date unavailable'; }
function nextRecurringDate(value, repeat, monthlyAnchorDay) { const next = new Date(value); if (repeat === 'Weekly') { next.setDate(next.getDate() + 7); return next; } const originalDay = monthlyAnchorDay ?? next.getDate(); next.setDate(1); next.setMonth(next.getMonth() + 1); const lastDay = new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate(); next.setDate(Math.min(originalDay, lastDay)); return next; }

export default function GenericEngine({ module }) {
  const table = tableFor[module.engine]; const isChecklist = module.engine === 'checklist'; const isStreak = module.engine === 'streakTracker'; const isSaved = module.engine === 'savedItems'; const isDue = module.engine === 'dueDateTracker';
  const listProfile = module.listExperience; const [user, setUser] = useState(null); const [records, setRecords] = useState([]); const [title, setTitle] = useState(''); const [date, setDate] = useState(day()); const [content, setContent] = useState(''); const [tags, setTags] = useState(''); const [fields, setFields] = useState({}); const [activeHabit, setActiveHabit] = useState('default'); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('active'); const [groupFilter, setGroupFilter] = useState('all'); const [sort, setSort] = useState('smart'); const [editing, setEditing] = useState(null); const [undo, setUndo] = useState(null); const [status, setStatus] = useState(isSupabaseConfigured ? 'Connecting...' : 'Supabase configuration is required.');
  const refresh = async (active = user) => { if (active) setRecords(await listRecords(table, active.id, module.id)); };
  useEffect(() => { if (!isSupabaseConfigured) return; getAnonymousUser().then(async (active) => { setUser(active); await refresh(active); setStatus(''); }).catch((error) => setStatus(error.message)); }, [module.id]);
  const streakScope = namedStreakScope(module); const selectedHabit = streakScope ? activeHabit.trim() || 'default' : 'default'; const streakRecordField = streakScope?.recordField ?? 'habit_key'; const scopedStreakRecords = streakScope ? records.filter((record) => (record[streakRecordField] || 'default') === selectedHabit) : records; const habitKeys = useMemo(() => streakScope ? [...new Set([...records.map((record) => record[streakRecordField] || 'default'), selectedHabit])].sort() : [], [records, streakScope, streakRecordField, selectedHabit]); const completedToday = scopedStreakRecords.some((record) => record.completed_on === day()); const currentStreak = useMemo(() => streak(scopedStreakRecords), [scopedStreakRecords]); const bestStreak = useMemo(() => { let best = 0; let run = 0; const sorted = [...new Set(scopedStreakRecords.map((record) => record.completed_on))].sort(); let previous = null; sorted.forEach((item) => { if (previous && (new Date(item) - new Date(previous)) / 86400000 === 1) run += 1; else run = 1; best = Math.max(best, run); previous = item; }); return best; }, [scopedStreakRecords]);
  const week = useMemo(() => Array.from({ length: 7 }, (_, index) => { const dateValue = day(addDays(new Date(), index - 6)); return { dateValue, done: scopedStreakRecords.some((record) => record.completed_on === dateValue) }; }), [scopedStreakRecords]);
  const visible = useMemo(() => records.filter((record) => { const data = values(record); const haystack = [record.title, record.content, record.note, ...Object.values(data), ...(record.tags ?? [])].join(' ').toLowerCase(); if (!haystack.includes(query.toLowerCase())) return false; if (isChecklist && filter === 'active') return !record.is_complete && !record.archived_at; if (isChecklist && filter === 'done') return record.is_complete && !record.archived_at; if (isChecklist && filter === 'archived') return Boolean(record.archived_at); if (isDue && filter === 'active') return !record.is_complete; if (isDue && filter === 'done') return record.is_complete; if (isSaved && filter === 'favorites') return record.metadata?.favorite; const savedFilter = isSaved ? matchesConfiguredFilter(data, filter, module.savedBehavior?.filters, new Date()) : undefined; if (savedFilter !== undefined) return savedFilter; if (isSaved && groupFilter !== 'all' && !(record.tags ?? []).includes(groupFilter)) return false; const listFilter = isChecklist ? matchesConfiguredFilter(data, filter, listProfile?.filters, new Date()) : undefined; if (listFilter !== undefined) return !record.is_complete && listFilter; if (isChecklist && listProfile?.statuses?.includes(filter)) return data.status === filter; if (isChecklist && groupFilter !== 'all') return String(data[listProfile?.groupField] ?? 'Unsorted') === groupFilter; if (isDue && filter === 'overdue') return !record.is_complete && record.due_at && new Date(record.due_at) < new Date(day()); if (isDue && filter === 'upcoming') return !record.is_complete && record.due_at && record.due_at >= day() && record.due_at <= day(addDays(new Date(), 7)); return true; }).sort((a, b) => { if (isDue && filter !== 'done') return String(a.due_at ?? '9999-12-31').localeCompare(String(b.due_at ?? '9999-12-31')); if (isChecklist && (filter === 'done' || filter === 'archived')) return new Date(b.archived_at ?? b.completed_at ?? b.created_at) - new Date(a.archived_at ?? a.completed_at ?? a.created_at); if (!isChecklist || sort === 'newest') return new Date(b.created_at) - new Date(a.created_at); if (sort === 'title') return a.title.localeCompare(b.title); const field = listProfile?.dateField; if (field) return String(values(a)[field] || '9999-12-31').localeCompare(String(values(b)[field] || '9999-12-31')); return new Date(b.created_at) - new Date(a.created_at); }), [records, query, filter, groupFilter, sort, isChecklist, isDue, isSaved, listProfile, module.savedBehavior]);
  const groups = useMemo(() => { if (!isChecklist || !listProfile) return []; const field = listProfile.groupField; const names = [...new Set([...listProfile.groupOrder, ...visible.map((r) => String(values(r)[field] ?? 'Unsorted'))])]; return names.filter(Boolean).map((name) => [name, visible.filter((record) => String(values(record)[field] ?? 'Unsorted') === name)]).filter(([, items]) => items.length); }, [isChecklist, listProfile, visible]);
  const upcomingCount = isDue ? records.filter((r) => !r.is_complete && r.due_at && new Date(r.due_at) >= new Date(day()) && new Date(r.due_at) <= addDays(new Date(), 7)).length : 0;
  async function save(event) { event.preventDefault(); if (!user || (isStreak ? completedToday : !title.trim())) return; let nextFields = { ...fields }; if (streakScope) nextFields[streakScope.field] = selectedHabit; nextFields = applyAutoFields(nextFields, module.savedBehavior?.autoFields); const base = { user_id: user.id, module_id: module.id }; let payload;
    if (isChecklist) payload = { ...base, title, is_complete: false, completed_at: null, archived_at: null, fields: nextFields };
    if (isStreak) payload = { ...base, completed_on: day(), note: content || null, fields: nextFields, ...(streakScope ? { [streakRecordField]: selectedHabit } : {}) };
    if (isSaved) payload = { ...base, title, content: content || null, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean), metadata: nextFields };
    if (isDue) payload = { ...base, title, due_at: date || null, is_complete: false, completed_at: null, metadata: nextFields };
    try { if (editing) { const patch = isChecklist ? { title, fields: nextFields } : isSaved ? { title, content: content || null, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean), metadata: nextFields } : isDue ? { title, due_at: date || null, metadata: nextFields } : { note: content || null, fields: nextFields }; await updateRecord(table, editing.id, patch); } else await addRecord(table, payload); setTitle(''); setContent(''); setTags(''); setFields({}); setDate(day()); setEditing(null); await refresh(); } catch (error) { setStatus(error.message); } }
  async function toggle(record) { try { const repeatField = recurrenceField(module); if (isDue && repeatField && record.metadata?.[repeatField] && record.due_at) { if (record.is_complete) { setStatus('Past recurring occurrences are preserved. Edit the next scheduled occurrence instead.'); return; } const completedAt = new Date().toISOString(); const recurrenceRootId = record.metadata?.recurrenceRootId ?? record.id; const recurrenceDayOfMonth = record.metadata?.recurrenceDayOfMonth ?? new Date(record.due_at).getDate(); const metadata = { ...record.metadata, recurrenceRootId, recurrenceDayOfMonth }; await updateRecord(table, record.id, { is_complete: true, completed_at: completedAt, metadata }); await addRecord(table, { user_id: user.id, module_id: module.id, title: record.title, due_at: day(nextRecurringDate(record.due_at, record.metadata[repeatField], recurrenceDayOfMonth)), is_complete: false, completed_at: null, metadata }); } else { const nextComplete = !record.is_complete; const patch = { is_complete: nextComplete }; if (isChecklist) { patch.completed_at = nextComplete ? new Date().toISOString() : null; patch.archived_at = null; } if (isDue) patch.completed_at = nextComplete ? new Date().toISOString() : null; if (isChecklist && nextComplete) { const fieldsPatch = completionFieldPatch(listProfile, record); if (fieldsPatch) patch.fields = fieldsPatch; } await updateRecord(table, record.id, patch); } await refresh(); } catch (error) { setStatus(error.message); } }
  async function clearCompleted() { const completed = records.filter((record) => record.is_complete && !record.archived_at); if (!completed.length || !window.confirm(`Archive ${completed.length} completed item${completed.length === 1 ? '' : 's'}? They will remain in Archived history.`)) return; try { setUndo(completed); const archivedAt = new Date().toISOString(); await Promise.all(completed.map((record) => updateRecord(table, record.id, { archived_at: archivedAt }))); await refresh(); } catch (error) { setStatus(error.message); } }
  async function restoreCompleted() { if (!undo) return; try { await Promise.all(undo.map((record) => updateRecord(table, record.id, { archived_at: null }))); setUndo(null); await refresh(); } catch (error) { setStatus(error.message); } }
  async function toggleFavorite(record) { try { await updateRecord(table, record.id, { metadata: { ...record.metadata, favorite: !record.metadata?.favorite } }); await refresh(); } catch (error) { setStatus(error.message); } }
  function edit(record) { setEditing(record); setTitle(record.title ?? ''); setContent(record.content ?? record.note ?? ''); setTags((record.tags ?? []).join(', ')); setDate(record.due_at ?? day()); setFields(values(record)); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const filterOptions = [...new Set([...(isSaved ? ['all', 'favorites', ...(module.savedBehavior?.filters ?? []).map((item) => item.id)] : isChecklist ? ['active', 'done', 'archived', ...(listProfile?.filters ?? []).map((item) => item.id), ...(listProfile?.statuses ?? [])] : isDue ? ['active', 'done', 'overdue', 'upcoming'] : [])])];
  const summary = isStreak ? `${currentStreak}-day streak` : isDue ? `${upcomingCount} due in 7 days` : `${records.filter((r) => !r.is_complete && !r.archived_at).length} active`;
  return <main className={`tracker-shell accent-${module.accent}`}><section className="suite-grid generic-suite">
    <header className="suite-header"><span className="icon-chip">{module.icon}</span><div><span className="eyebrow">{module.engine === 'savedItems' ? 'Your library' : module.engine === 'dueDateTracker' ? 'Plan ahead' : module.engine}</span><h1>{module.title}</h1></div></header>
    <section className="suite-card suite-overview"><span className="section-label">Overview</span><strong>{isStreak ? (completedToday ? 'Done today' : 'Ready') : isSaved ? records.length : summary}</strong><small>{isStreak ? `Best streak: ${bestStreak} days` : isSaved ? `${records.length} saved item${records.length === 1 ? '' : 's'}` : summary}</small>{isStreak && <><div className="mini-metrics"><span>Current <b>{currentStreak} days</b></span><span>Best <b>{bestStreak} days</b></span></div><div className="week-dots">{week.map((item) => <i key={item.dateValue} className={item.done ? 'done' : ''} title={item.dateValue} />)}</div>{streakScope && <div className="habit-switcher"><small>Viewing habit</small><div>{habitKeys.map((habit) => <button type="button" key={habit} className={selectedHabit === habit ? 'active' : ''} onClick={() => { setActiveHabit(habit); setFields({ ...fields, [streakScope.field]: habit }); }}>{habit}</button>)}</div></div>}</>}</section>
    {isStreak && <StreakCalendar completedDates={scopedStreakRecords.map((record) => record.completed_on)} title={streakScope ? `${selectedHabit} history` : 'Check-in calendar'} />}
    <form className="suite-card composer-card" onSubmit={save}><span className="section-label">{editing ? 'Edit item' : labelFor[module.engine]}</span>{!isStreak && <Field field={{ label: module.savedBehavior?.presentation?.titleLabel ?? 'Title', type: 'text' }} value={title} onChange={setTitle} />}{isDue && <Field field={{ label: 'Due date', type: 'date' }} value={date} onChange={setDate} />}{(isSaved || isStreak) && <Field field={{ label: module.savedBehavior?.presentation?.notesLabel ?? 'Notes', type: 'text' }} value={content} onChange={setContent} />}{module.fields.map((field) => <Field key={field.id} field={field} value={streakScope && field.id === streakScope.field ? selectedHabit : fields[field.id]} onChange={(value) => { if (streakScope && field.id === streakScope.field) setActiveHabit(value); setFields({ ...fields, [field.id]: value }); }} />)}{isSaved && <Field field={{ label: 'Tags (comma separated)', type: 'text' }} value={tags} onChange={setTags} />}<button disabled={!user || (isStreak && completedToday)}>{editing ? 'Save changes' : isStreak ? (completedToday ? 'Checked in' : 'Mark done today') : labelFor[module.engine]}</button>{editing && <button className="text-button" type="button" onClick={() => setEditing(null)}>Cancel</button>}</form>
    {(isChecklist || isDue || isSaved) && <section className="suite-card filter-card"><span className="section-label">Find & filter</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search this module" /><div className="filter-row">{filterOptions.map((item) => <button type="button" key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div>{isSaved && <label className="filter-select">Tag <select value={groupFilter} onChange={(e) => setGroupFilter(e.target.value)}><option value="all">All tags</option>{[...new Set(records.flatMap((record) => record.tags ?? []))].sort().map((tag) => <option key={tag}>{tag}</option>)}</select></label>}{isChecklist && listProfile && <><label className="filter-select">Group <select value={groupFilter} onChange={(e) => setGroupFilter(e.target.value)}><option value="all">All {listProfile.groupField}s</option>{[...new Set(records.map((record) => String(values(record)[listProfile.groupField] ?? 'Unsorted')))].map((item) => <option key={item}>{item}</option>)}</select></label><label className="filter-select">Sort <select value={sort} onChange={(e) => setSort(e.target.value)}><option value="smart">Smart order</option><option value="newest">Newest</option><option value="title">Title</option></select></label></>}</section>}
    <section className="suite-card suite-records"><div className="chart-title"><div><span className="section-label">{isSaved ? 'Library' : isStreak ? 'Check-in history' : isDue ? 'Schedule' : filter === 'archived' ? 'Archived history' : filter === 'done' ? 'Completed history' : 'Items'}</span><h2>{visible.length} shown</h2></div>{isChecklist && <button className="text-button" type="button" onClick={clearCompleted}>Archive completed</button>}</div>{(isChecklist ? groups : [['All items', visible]]).map(([group, items]) => <div className="record-group" key={group}>{isChecklist && <h3>{group}</h3>}<ul>{items.map((record) => { const data = values(record); const overdue = isDue && !record.is_complete && record.due_at && new Date(record.due_at) < new Date(day()); const daysLeft = record.due_at ? Math.ceil((new Date(record.due_at) - new Date(day())) / 86400000) : null; return <li key={record.id} className={overdue ? 'is-overdue' : ''}>{(isChecklist || isDue) && <button className="check" onClick={() => toggle(record)}>{record.is_complete ? '✓' : '○'}</button>}<span><strong>{record.title ?? record.note ?? 'Check-in'}</strong><small>{record.due_at ? `${overdue ? 'Overdue · ' : daysLeft === 0 ? 'Due today · ' : `${daysLeft} days left · `}${new Date(record.due_at).toLocaleDateString()} · ` : ''}{Object.entries(data).filter(([key, value]) => value && key !== 'favorite').map(([key, value]) => `${key}: ${value}`).join(' · ') || record.content || record.note || (record.tags ?? []).join(', ') || 'No details'}{isChecklist && ` · ${checklistHistoryLabel(record)}`}{isDue && record.is_complete && record.completed_at ? ` · Completed ${new Date(record.completed_at).toLocaleDateString()}` : ''}</small>{isSaved && record.tags?.length ? <em>{record.tags.map((tag) => `#${tag}`).join(' ')}</em> : null}</span>{isSaved && <button aria-label="Toggle favorite" onClick={() => toggleFavorite(record)}>{record.metadata?.favorite ? '★' : '☆'}</button>}<button onClick={() => edit(record)}>Edit</button><button aria-label="Delete item" onClick={() => removeRecord(table, record.id).then(refresh)}>×</button></li>; })}</ul></div>)}{!visible.length && <p className="empty-copy">Nothing here yet. Add the first item above.</p>}</section>{undo && <p className="undo">Completed items archived. <button onClick={restoreCompleted}>Undo</button></p>}{status && <p className="status">{status}</p>}
  </section></main>;
}
