// This compact catalog is deliberately data-only so the Edge Function can
// present the same human labels as the app without importing React code.
const goalProgressProfiles = {
  calories: { compatible: true, direction: 'increase', baseline: 'zero' }, budget: { compatible: true, direction: 'increase', baseline: 'zero' }, water: { compatible: true, direction: 'increase', baseline: 'zero' }, weight: { compatible: true, direction: 'decrease', baseline: 'first_record' }, steps: { compatible: true, direction: 'increase', baseline: 'zero' }, 'time-tracking': { compatible: true, direction: 'increase', baseline: 'zero' }, savings: { compatible: true, direction: 'increase', baseline: 'zero' }, 'net-worth': { compatible: true, direction: 'increase', baseline: 'first_record' }, investments: { compatible: true, direction: 'increase', baseline: 'zero' }, debt: { compatible: false, direction: 'decrease', baseline: 'ledger' },
};

export const moduleCatalog = [
  ['calories', 'Calories', 'entryTracker', 'kcal', 'sum'], ['budget', 'Budget', 'entryTracker', 'USD', 'net'], ['water', 'Water intake', 'entryTracker', 'ml', 'sum'], ['weight', 'Weight', 'entryTracker', 'kg', 'latest'], ['steps', 'Steps', 'entryTracker', 'steps', 'sum'], ['time-tracking', 'Time tracking', 'entryTracker', 'min', 'sum'], ['subscriptions', 'Subscriptions', 'entryTracker', 'USD', 'sum'], ['savings', 'Savings goal', 'entryTracker', 'USD', 'net'], ['net-worth', 'Net worth', 'entryTracker', 'USD', 'latest'], ['investments', 'Investments', 'entryTracker', 'USD', 'sum'],
  ['todo', 'Todo', 'checklist', 'items', 'count'], ['grocery', 'Grocery list', 'checklist', 'items', 'count'], ['watchlist', 'Watchlist', 'checklist', 'items', 'count'], ['bucket-list', 'Bucket list', 'checklist', 'items', 'count'], ['gift-ideas', 'Gift ideas', 'checklist', 'items', 'count'],
  ['exercise', 'Exercise', 'streakTracker', 'check-ins', 'streak'], ['medication', 'Medication', 'streakTracker', 'check-ins', 'streak'], ['meditation', 'Meditation', 'streakTracker', 'check-ins', 'streak'], ['habits', 'Habit tracker', 'streakTracker', 'check-ins', 'streak'], ['language', 'Language learning', 'streakTracker', 'check-ins', 'streak'], ['skill-practice', 'Skill practice', 'streakTracker', 'check-ins', 'streak'], ['gratitude', 'Gratitude log', 'streakTracker', 'check-ins', 'streak'],
  ['links', 'Link saver', 'savedItems', 'saved items', 'count'], ['journal', 'Journal', 'savedItems', 'saved items', 'count'], ['reading-list', 'Reading list', 'savedItems', 'saved items', 'count'], ['contacts', 'Contacts', 'savedItems', 'saved items', 'count'], ['recipes', 'Recipe box', 'savedItems', 'saved items', 'count'], ['ideas', 'Idea inbox', 'savedItems', 'saved items', 'count'], ['quotes', 'Quote collector', 'savedItems', 'saved items', 'count'],
  ['debt', 'Debt payoff', 'dueDateTracker', 'items', 'ledger'], ['remittance', 'Remittance log', 'dueDateTracker', 'items', 'count'], ['chores', 'Chore schedule', 'dueDateTracker', 'items', 'count'], ['packages', 'Package tracker', 'dueDateTracker', 'items', 'count'], ['warranties', 'Warranty tracker', 'dueDateTracker', 'items', 'count'], ['documents', 'Document expiry', 'dueDateTracker', 'items', 'count'], ['maintenance', 'Vehicle maintenance', 'dueDateTracker', 'items', 'count'], ['courses', 'Course tracker', 'dueDateTracker', 'items', 'count'],
].map(([id, title, engine, unit, aggregation]) => ({ id, title, engine, unit, aggregation, goalProgress: goalProgressProfiles[id] ?? { compatible: false, direction: 'increase', baseline: 'zero' } }));

export const catalogById = Object.fromEntries(moduleCatalog.map((module) => [module.id, module]));
export const tableByEngine = { entryTracker: 'entry_records', checklist: 'checklist_items', streakTracker: 'streak_checkins', savedItems: 'saved_items', dueDateTracker: 'due_items' };
