import { useEffect, useMemo, useState } from 'react';
import { engines, modules } from '../config/modules';
import { getAnonymousUser, supabase } from '../data/supabaseClient';

const tableByEngine = { entryTracker: 'entry_records', checklist: 'checklist_items', streakTracker: 'streak_checkins', savedItems: 'saved_items', dueDateTracker: 'due_items' };
const today = new Date().toISOString().slice(0, 10);

export default function Dashboard({ onOpen }) {
  const [counts, setCounts] = useState({}); const [actions, setActions] = useState({ overdue: [], upcoming: [], activeLists: 0, habits: 0 }); const [status, setStatus] = useState('');
  useEffect(() => { getAnonymousUser().then(async (user) => { const tables = [...new Set(Object.values(tableByEngine))]; const results = await Promise.all(tables.map(async (table) => { const { data, error } = await supabase.from(table).select('*').eq('user_id', user.id); if (error) throw error; return [table, data ?? []]; })); const byTable = Object.fromEntries(results); const next = {}; Object.values(byTable).flat().forEach((row) => { next[row.module_id] = (next[row.module_id] ?? 0) + 1; }); const due = byTable.due_items ?? []; const checkins = byTable.streak_checkins ?? []; const lists = byTable.checklist_items ?? []; setCounts(next); setActions({ overdue: due.filter((r) => !r.is_complete && r.due_at && r.due_at < today).sort((a, b) => a.due_at.localeCompare(b.due_at)).slice(0, 5), upcoming: due.filter((r) => !r.is_complete && r.due_at && r.due_at >= today).sort((a, b) => a.due_at.localeCompare(b.due_at)).slice(0, 5), activeLists: lists.filter((r) => !r.is_complete).length, habits: checkins.filter((r) => r.completed_on === today).length }); }).catch((error) => setStatus(error.message)); }, []);
  const actionCount = actions.overdue.length + actions.upcoming.length;
  const actionCards = useMemo(() => [{ label: 'Overdue', value: actions.overdue.length, tone: 'urgent' }, { label: 'Due next', value: actions.upcoming.length, tone: 'soon' }, { label: 'Open list items', value: actions.activeLists, tone: 'neutral' }, { label: 'Habit check-ins', value: actions.habits, tone: 'neutral' }], [actions]);
  return <main className="tracker-shell dashboard"><section className="suite-grid dashboard-grid"><header className="suite-header"><div><span className="eyebrow">Your everyday overview</span><h1>Today</h1></div><small>{actionCount ? `${actionCount} items need attention` : 'You are all caught up.'}</small></header><section className="dashboard-actions">{actionCards.map((card) => <div className={`action-stat ${card.tone}`} key={card.label}><small>{card.label}</small><strong>{card.value}</strong></div>)}</section><section className="suite-card dashboard-agenda"><div className="chart-title"><div><span className="section-label">Attention</span><h2>Deadlines</h2></div></div>{[...actions.overdue, ...actions.upcoming].length ? <ul>{[...actions.overdue, ...actions.upcoming].map((item) => <li key={item.id}><span><strong>{item.title}</strong><small>{item.due_at < today ? 'Overdue' : `Due ${new Date(item.due_at).toLocaleDateString()}`}</small></span><button onClick={() => onOpen(item.module_id)}>Open</button></li>)}</ul> : <p className="empty-copy">No upcoming deadlines. Nice.</p>}</section>{Object.entries(engines).map(([engine, title]) => <section key={engine} className="dashboard-group"><h2>{title}</h2><div className="module-grid">{modules.filter((module) => module.engine === engine).map((module) => <button className={`module-card accent-${module.accent}`} key={module.id} onClick={() => onOpen(module.id)}><span className="icon-chip">{module.icon}</span><strong>{module.title}</strong><small>{counts[module.id] ?? 0} record{counts[module.id] === 1 ? '' : 's'}</small></button>)}</div></section>)}{status && <p className="status">{status}</p>}</section></main>;
}
