const currencies = ['USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'SGD'];
const budgetCategories = ['Food', 'Transport', 'Bills', 'Shopping', 'Health', 'Entertainment', 'Other'];

// TrackerSuite reads these profiles rather than module names, so new tracker
// experiences stay configuration-led while sharing the same engine and tables.
const trackerProfiles = {
  water: { kind: 'water', units: ['ml', 'oz'], presets: [250, 500, 750], streak: true },
  weight: { kind: 'weight', units: ['kg', 'lb'], trend: true },
  steps: { kind: 'steps', presets: [500, 1000, 2500], personalBest: true },
  'time-tracking': { kind: 'time', timer: true, reports: true },
  subscriptions: { kind: 'subscriptions', lifecycle: true },
  savings: { kind: 'savings', forecast: true },
  'net-worth': { kind: 'netWorth', breakdown: true },
  investments: { kind: 'investments', accounts: ['Rakuten Securities', 'NISA', 'iDeCo', 'Brokerage', 'Crypto exchange', 'Other'], assetTypes: ['Mutual fund', 'ETF', 'Stock', 'Bond', 'Crypto', 'Cash', 'Other'], snapshots: true },
};

const engineProfiles = {
  todo: { fields: [{ id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High'] }, { id: 'dueDate', label: 'Due date', type: 'date' }, { id: 'notes', label: 'Notes', type: 'text' }] },
  grocery: { fields: [{ id: 'quantity', label: 'Quantity / unit', type: 'text' }, { id: 'category', label: 'Category', type: 'select', options: ['Produce', 'Pantry', 'Dairy', 'Frozen', 'Household', 'Other'] }, { id: 'store', label: 'Store / aisle', type: 'text' }] },
  watchlist: { fields: [{ id: 'type', label: 'Type', type: 'select', options: ['Book', 'Movie', 'Show'] }, { id: 'status', label: 'Status', type: 'select', options: ['Want to watch', 'In progress', 'Finished'] }, { id: 'where', label: 'Source URL', type: 'url' }, { id: 'rating', label: 'Your rating', type: 'number' }] },
  'bucket-list': { fields: [{ id: 'category', label: 'Category', type: 'text' }, { id: 'status', label: 'Status', type: 'select', options: ['Someday', 'Planned', 'Done'] }, { id: 'targetDate', label: 'Target date', type: 'date' }, { id: 'cost', label: 'Cost estimate', type: 'number' }, { id: 'nextAction', label: 'Next action', type: 'text' }] },
  'gift-ideas': { fields: [{ id: 'person', label: 'For whom?', type: 'text' }, { id: 'occasion', label: 'Occasion', type: 'text' }, { id: 'occasionDate', label: 'Occasion date', type: 'date' }, { id: 'budget', label: 'Budget', type: 'number' }, { id: 'source', label: 'Source / link', type: 'url' }, { id: 'status', label: 'Status', type: 'select', options: ['Idea', 'To buy', 'Purchased', 'Given'] }] },
  exercise: { fields: [{ id: 'duration', label: 'Minutes', type: 'number' }, { id: 'workoutType', label: 'Workout type', type: 'select', options: ['Strength', 'Cardio', 'Mobility', 'Sport', 'Walk', 'Other'] }, { id: 'effort', label: 'Effort', type: 'select', options: ['Easy', 'Moderate', 'Hard'] }] }, medication: { fields: [{ id: 'dose', label: 'Dose / reminder', type: 'text' }, { id: 'time', label: 'Time taken', type: 'text' }] }, meditation: { fields: [{ id: 'duration', label: 'Minutes', type: 'number' }, { id: 'style', label: 'Style', type: 'select', options: ['Breathing', 'Guided', 'Body scan', 'Other'] }] }, language: { fields: [{ id: 'duration', label: 'Minutes', type: 'number' }, { id: 'topic', label: 'Topic', type: 'text' }] }, 'skill-practice': { fields: [{ id: 'duration', label: 'Minutes', type: 'number' }, { id: 'project', label: 'Project / skill', type: 'text' }] },
  links: { fields: [{ id: 'url', label: 'URL', type: 'url', required: true }, { id: 'type', label: 'Type', type: 'select', options: ['Article', 'YouTube', 'Instagram', 'Other'] }, { id: 'status', label: 'Reading state', type: 'select', options: ['Unread', 'In progress', 'Finished'] }] }, journal: { fields: [{ id: 'mood', label: 'Mood', type: 'select', options: ['Great', 'Good', 'Okay', 'Low'] }, { id: 'entryType', label: 'Entry type', type: 'select', options: ['Reflection', 'Daily note', 'Memory', 'Lesson'] }] }, 'reading-list': { fields: [{ id: 'progress', label: 'Progress %', type: 'number' }, { id: 'status', label: 'Status', type: 'select', options: ['Want to read', 'Reading', 'Finished'] }] }, contacts: { fields: [{ id: 'phone', label: 'Phone', type: 'tel' }, { id: 'email', label: 'Email', type: 'email' }, { id: 'organization', label: 'Organization / context', type: 'text' }, { id: 'birthday', label: 'Birthday', type: 'date' }, { id: 'lastTalked', label: 'Last talked', type: 'date' }] }, recipes: { fields: [{ id: 'source', label: 'Source URL', type: 'url' }, { id: 'ingredients', label: 'Ingredients', type: 'text' }, { id: 'cuisine', label: 'Cuisine', type: 'text' }, { id: 'course', label: 'Course', type: 'select', options: ['Breakfast', 'Lunch', 'Dinner', 'Snack', 'Dessert', 'Other'] }] }, ideas: { fields: [{ id: 'status', label: 'Status', type: 'select', options: ['Inbox', 'Review', 'Promoted', 'Archived'] }] }, quotes: { fields: [{ id: 'author', label: 'Author', type: 'text' }, { id: 'source', label: 'Source', type: 'text' }] },
  debt: { fields: [{ id: 'amount', label: 'Original amount owed', type: 'number', required: true }] }, remittance: { fields: [{ id: 'amount', label: 'Amount', type: 'number' }, { id: 'recipient', label: 'Recipient', type: 'text' }, { id: 'sent', label: 'Sent date', type: 'date' }, { id: 'state', label: 'State', type: 'select', options: ['To send', 'Sent', 'Received'] }] }, chores: { fields: [{ id: 'repeat', label: 'Repeat', type: 'select', options: ['Weekly', 'Monthly'] }, { id: 'area', label: 'Area', type: 'text' }] }, packages: { fields: [{ id: 'tracking', label: 'Tracking number', type: 'text' }, { id: 'carrier', label: 'Carrier', type: 'text' }, { id: 'trackingUrl', label: 'Tracking URL', type: 'url' }, { id: 'status', label: 'Status', type: 'select', options: ['Ordered', 'Shipped', 'Delivered'] }] }, warranties: { fields: [{ id: 'store', label: 'Store / provider', type: 'text' }, { id: 'receipt', label: 'Receipt / reference', type: 'text' }] }, documents: { fields: [{ id: 'documentType', label: 'Document type', type: 'text' }, { id: 'issuer', label: 'Issuer', type: 'text' }] }, maintenance: { fields: [{ id: 'asset', label: 'Vehicle / bike', type: 'text' }, { id: 'serviceType', label: 'Service type', type: 'text' }] }, courses: { fields: [{ id: 'progress', label: 'Progress %', type: 'number' }, { id: 'provider', label: 'Provider', type: 'text' }, { id: 'credential', label: 'Certificate / credential', type: 'text' }] },
};

const listProfiles = {
  todo: { kind: 'todo', groupField: 'priority', groupOrder: ['High', 'Medium', 'Low'], dateField: 'dueDate', statuses: [] },
  grocery: { kind: 'grocery', groupField: 'category', groupOrder: ['Produce', 'Pantry', 'Dairy', 'Frozen', 'Household', 'Other'], statuses: [] },
  watchlist: { kind: 'watchlist', groupField: 'status', groupOrder: ['Want to watch', 'In progress', 'Finished'], statuses: ['Want to watch', 'In progress', 'Finished'] },
  'bucket-list': { kind: 'bucket', groupField: 'status', groupOrder: ['Planned', 'Someday', 'Done'], statuses: ['Someday', 'Planned', 'Done'] },
  'gift-ideas': { kind: 'gifts', groupField: 'person', groupOrder: [], statuses: ['Idea', 'To buy', 'Purchased', 'Given'] },
};

const entry = (id, title, icon, accent, entryTracker) => ({ id, title, icon, accent, engine: 'entryTracker', entryTracker: { ...entryTracker, experience: { ...entryTracker.experience, ...trackerProfiles[id] } } });
const withProfile = (id, fields) => [...(engineProfiles[id]?.fields ?? []), ...fields.filter((field) => !(engineProfiles[id]?.fields ?? []).some((profileField) => profileField.id === field.id))];
const checklist = (id, title, icon, fields = [], listBehavior = {}) => ({ id, title, icon, accent: 'pink', engine: 'checklist', fields: withProfile(id, fields), listExperience: { ...listProfiles[id], ...listBehavior } });
const streak = (id, title, icon, fields = [], streakBehavior = {}) => ({ id, title, icon, accent: 'green', engine: 'streakTracker', fields: withProfile(id, fields), streakBehavior });
const saved = (id, title, icon, fields = [], savedBehavior = {}) => ({ id, title, icon, accent: 'blue', engine: 'savedItems', fields: withProfile(id, fields), savedBehavior });
const due = (id, title, icon, fields = [], dueBehavior = {}) => ({ id, title, icon, accent: 'blue', engine: 'dueDateTracker', fields: withProfile(id, fields), dueBehavior });

const daily = (label, unit, target) => ({ value: { label, unit, inputMode: 'decimal', step: 1, minimum: 0, precision: 0, displayFormat: 'number' }, aggregation: { operation: 'sum', period: 'calendar_day' }, goal: { enabled: true, target, label: 'Daily goal' }, chart: { enabled: true, type: 'bar', period: 'last_n_days', count: 7, aggregation: 'sum' }, fields: [] });

// Global Goals uses this data rather than guessing whether a larger number is
// better. Snapshot trackers start from their first recorded value; cumulative
// trackers start from zero. Debt is intentionally not compatible yet because
// its payment ledger is not an EntryTracker value stream.
const goalProgressProfiles = {
  calories: { compatible: true, direction: 'increase', baseline: 'zero' },
  budget: { compatible: true, direction: 'increase', baseline: 'zero' },
  water: { compatible: true, direction: 'increase', baseline: 'zero' },
  weight: { compatible: true, direction: 'decrease', baseline: 'first_record' },
  steps: { compatible: true, direction: 'increase', baseline: 'zero' },
  'time-tracking': { compatible: true, direction: 'increase', baseline: 'zero' },
  savings: { compatible: true, direction: 'increase', baseline: 'zero' },
  'net-worth': { compatible: true, direction: 'increase', baseline: 'first_record' },
  investments: { compatible: true, direction: 'increase', baseline: 'zero' },
  debt: { compatible: false, direction: 'decrease', baseline: 'ledger' },
};

const moduleDefinitions = [
  entry('calories', 'Calories', '◒', 'green', { ...daily('Calories', 'kcal', 2000), experience: { quickAdd: [100, 250, 500], meals: ['Breakfast', 'Lunch', 'Dinner', 'Snacks'], notes: true, allowSkip: true, allowClearDay: true, personalTarget: true, calorieBurn: true, deficitMode: true } }),
  entry('budget', 'Budget', '◈', 'pink', { value: { label: 'Transaction', unit: 'USD', inputMode: 'decimal', step: 0.01, minimum: 0, precision: 2, displayFormat: 'currency' }, aggregation: { operation: 'sum', period: 'all_time' }, goal: { enabled: false }, chart: { enabled: true, type: 'bar', period: 'last_n_days', count: 7, aggregation: 'sum' }, fields: [{ id: 'category', label: 'Category', type: 'select', required: true, options: budgetCategories }], currency: { enabled: true, base: 'USD', options: currencies }, experience: { kind: 'budget', quickAdd: [5, 10, 25, 50], categories: budgetCategories, analytics: true }, recurrence: { enabled: false }, dueDate: { enabled: false } }),
  entry('water', 'Water intake', '◌', 'green', daily('Water', 'ml', 2000)),
  entry('weight', 'Weight', '◍', 'green', { value: { label: 'Weight', unit: 'kg', inputMode: 'decimal', step: 0.1, minimum: 0, precision: 1, displayFormat: 'number' }, aggregation: { operation: 'latest', period: 'all_time' }, goal: { enabled: false }, chart: { enabled: true, type: 'line', period: 'last_n_days', count: 30, aggregation: 'latest' }, fields: [] }),
  entry('steps', 'Steps', '⌁', 'green', daily('Steps', 'steps', 10000)),
  entry('time-tracking', 'Time tracking', '◷', 'green', { value: { label: 'Minutes', unit: 'min', inputMode: 'numeric', step: 1, minimum: 0, precision: 0, displayFormat: 'duration' }, aggregation: { operation: 'sum', period: 'calendar_day' }, goal: { enabled: false }, chart: { enabled: true, type: 'bar', period: 'last_n_days', count: 7, aggregation: 'sum' }, fields: [{ id: 'project', label: 'Project', type: 'text', required: true }, { id: 'task', label: 'Task', type: 'text', required: false }] }),
  entry('subscriptions', 'Subscriptions', '↻', 'pink', { value: { label: 'Cost', unit: 'USD', inputMode: 'decimal', step: 0.01, minimum: 0, precision: 2, displayFormat: 'currency' }, aggregation: { operation: 'sum', period: 'all_time' }, goal: { enabled: false }, chart: { enabled: false }, fields: [{ id: 'billingCycle', label: 'Billing cycle', type: 'select', required: true, options: ['Monthly', 'Yearly'] }, { id: 'dueDate', label: 'Next due date', type: 'date', required: true }], currency: { enabled: true, base: 'USD', options: currencies }, recurrence: { enabled: true }, dueDate: { enabled: true } }),
  entry('savings', 'Savings goal', '◎', 'pink', { value: { label: 'Savings added', unit: 'USD', inputMode: 'decimal', step: 0.01, minimum: 0, precision: 2, displayFormat: 'currency' }, aggregation: { operation: 'sum', period: 'all_time' }, goal: { enabled: true, target: 1000, label: 'Target' }, chart: { enabled: true, type: 'line', period: 'last_n_days', count: 30, aggregation: 'sum' }, fields: [], currency: { enabled: true, base: 'USD', options: currencies } }),
  entry('net-worth', 'Net worth', '◫', 'pink', { value: { label: 'Net worth', unit: 'USD', inputMode: 'decimal', step: 0.01, minimum: 0, precision: 2, displayFormat: 'currency' }, aggregation: { operation: 'latest', period: 'all_time' }, goal: { enabled: false }, chart: { enabled: true, type: 'line', period: 'last_n_days', count: 30, aggregation: 'latest' }, fields: [], currency: { enabled: true, base: 'USD', options: currencies } }),
  entry('investments', 'Investments', '◈', 'pink', { value: { label: 'Amount', unit: 'USD', inputMode: 'decimal', step: 0.01, minimum: 0, precision: 2, displayFormat: 'currency' }, aggregation: { operation: 'sum', period: 'all_time' }, goal: { enabled: true, target: 12000, label: 'Annual target' }, chart: { enabled: true, type: 'bar', period: 'last_n_days', count: 30, aggregation: 'sum' }, fields: [], currency: { enabled: true, base: 'USD', options: currencies } }),

  checklist('todo', 'Todo', '✓', [{ id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High'] }], { filters: [{ id: 'today', kind: 'date-equals', field: 'dueDate' }, { id: 'upcoming', kind: 'date-after', field: 'dueDate' }, { id: 'overdue', kind: 'date-before', field: 'dueDate' }] }), checklist('grocery', 'Grocery list', '⌑'), checklist('watchlist', 'Watchlist', '▻', [{ id: 'type', label: 'Type', type: 'select', options: ['Book', 'Movie', 'Show'] }], { filters: [{ id: 'next-up', kind: 'field-in', field: 'status', values: ['Want to watch', 'In progress'] }], completionUpdate: { field: 'status', value: 'Finished' }, linkFields: [{ field: 'where', label: 'Open source' }] }), checklist('bucket-list', 'Bucket list', '☆', [], { completionUpdate: { field: 'status', value: 'Done' } }), checklist('gift-ideas', 'Gift ideas', '♢', [{ id: 'person', label: 'For whom?', type: 'text' }], { completionUpdate: { field: 'status', value: 'Given' } }),
  streak('exercise', 'Exercise', '↟'), streak('medication', 'Medication', '✚'), streak('meditation', 'Meditation', '☽'), streak('habits', 'Habit tracker', '☀', [{ id: 'habit', label: 'Habit', type: 'text' }], { scope: { kind: 'named', field: 'habit' } }), streak('language', 'Language learning', '⌘'), streak('skill-practice', 'Skill practice', '✦'), streak('gratitude', 'Gratitude log', '♡', [{ id: 'reflection', label: 'What are you grateful for?', type: 'text' }]),
  saved('links', 'Link saver', '↗', [{ id: 'url', label: 'URL', type: 'url' }, { id: 'type', label: 'Type', type: 'select', options: ['Article', 'YouTube', 'Instagram', 'Other'] }], { autoFields: [{ source: 'url', target: 'type', detector: 'link-type' }], linkFields: [{ field: 'url', label: 'Open link' }] }), saved('journal', 'Journal', '✎', [], { presentation: { titleLabel: 'Title / date', notesLabel: 'Write freely' } }), saved('reading-list', 'Reading list', '☷', [{ id: 'progress', label: 'Progress %', type: 'number' }], { filters: [{ id: 'next-up', kind: 'field-in', field: 'status', values: ['Want to read', 'Reading'] }] }), saved('contacts', 'Contacts', '♙', [{ id: 'birthday', label: 'Birthday', type: 'date' }, { id: 'lastTalked', label: 'Last talked', type: 'date' }], { filters: [{ id: 'follow-up', kind: 'date-before-or-empty', field: 'lastTalked', days: 30 }] }), saved('recipes', 'Recipe box', '♨'), saved('ideas', 'Idea inbox', '✧', [], { filters: [{ id: 'review', kind: 'field-in', field: 'status', values: ['Review', 'Inbox'] }, { id: 'promoted', kind: 'field-equals', field: 'status', value: 'Promoted' }] }), saved('quotes', 'Quote collector', '❝'),
  due('debt', 'Debt payoff', '◒', [{ id: 'amount', label: 'Original amount owed', type: 'number', required: true }], { ledger: { amountField: 'amount' } }), due('remittance', 'Remittance log', '↝', [{ id: 'amount', label: 'Amount', type: 'number' }, { id: 'recipient', label: 'Recipient', type: 'text' }]), due('chores', 'Chore schedule', '⌂', [{ id: 'repeat', label: 'Repeat', type: 'select', options: ['Weekly', 'Monthly'] }], { recurrence: { field: 'repeat' } }), due('packages', 'Package tracker', '□', [{ id: 'tracking', label: 'Tracking number', type: 'text' }], { linkFields: [{ field: 'trackingUrl', label: 'Track package' }] }), due('warranties', 'Warranty tracker', '▣'), due('documents', 'Document expiry', '▤', [{ id: 'documentType', label: 'Document type', type: 'text' }]), due('maintenance', 'Vehicle maintenance', '⚙'), due('courses', 'Course tracker', '▱'),
];

export const modules = moduleDefinitions.map((module) => ({
  ...module,
  goalProgress: goalProgressProfiles[module.id] ?? { compatible: false, direction: 'increase', baseline: 'zero' },
}));

export const getModule = (moduleId) => modules.find((module) => module.id === moduleId);
export const engines = { entryTracker: 'Trackers', checklist: 'Lists', streakTracker: 'Streaks', savedItems: 'Saved', dueDateTracker: 'Due dates' };
